logging:
  level:
    root: info
    com.navi.mini.program.dao: debug

spring:
  datasource:
    url: jdbc:mysql://172.21.3.2:3306/mini?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
    username: root
    password: nangao2019-
    driverClassName: com.mysql.jdbc.Driver
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: false
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,log4j
    hikari:
      max-lifetime: 30000

  redis:
    database: 0
    host: 172.21.3.2
    port: 6379
    password: nangao
    timeout: 10000
    block-when-exhausted: true
    jedis:
      pool:
        max-active: 20
        max-wait-millis: 200
        max-idle: 20
        min-idle: 0

server:
  port: 8081
#  servlet:
#    context-path: /equipngy

# 微信配置
wechat:
  we-chat-access-token: weChatAccessTokenMiniDev
  ticket-token: ticketTokenMiniDev
#  app-id: wx38b00b683bf8be2d
#  app-secret: 91d189e9ec39403f778d0b4893ca76ca
  # 公司的
  app-id: wxfafe4f9b7bbffd7f
  app-secret: 93e63a4ccba1a30c2ac274bed73328a7

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

